### Sign up
POST http://localhost:8080/member/save
Content-Type: application/json

{
  "email": "test@test.com",
  "name": "tester",
  "password": "123123123"
}

### LoginTest
POST http://localhost:8080/member/doLogin
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "123123123"
}

> {%
    client.global.set("token", response.headers.valueOf("Authorization"));
 %}

### members
GET http://localhost:8080/member/list
Content-Type: application/json
Authorization: {{token}}

### create group chat room
POST http://localhost:8080/chat/room/group/create?roomName=testRoom
Content-Type: application/json
Authorization: {{token}}

### chat rooms
GET http://localhost:8080/chat/room/group/list
Content-Type: application/json
Authorization: {{token}}

### join room 1
POST http://localhost:8080/chat/room/group/1/join
Content-Type: application/json
Authorization: {{token}}

### room 1 participants
GET http://localhost:8080/chat/room/group/1/members
Content-Type: application/json
Authorization: {{token}}
